service: lift-static
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  index:
    handler: index.handler
    events:
#      - http:  'GET test'
      - httpApi: '*'

package:
  patterns:
    - '!node_modules'

constructs:
  upload:
    type: upload
#    apiGateway: rest
  landing:
    type: static-website
    path: dist
plugins:
    - serverless-lift
